services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  server:
    depends_on:
      - db
    build:
      context: .
      target: final
    env_file:
      - secrets/.env_deploy
    ports:
      - 8000:8000
    secrets:
      - cert
      - key
    volumes:
      - type: bind
        source: ./writing
        target: /writing
          
secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  cert:
    file: secrets/cert.pem
  key:
    file: secrets/key.pem


volumes:
    db_data: