services:
  server:
    build:
      context: .
      target: final
    image: jhb123/blog:290819
    env_file:
      - secrets/.env_deploy
    ports:
      - 8123:8000
    volumes:
      - type: bind
        source: ./writing
        target: /writing
      - type: volume
        source: db_data
        target: /db/site

volumes:
    db_data:
